# mcmap/Makefile.posix  -*- mode: makefile -*-

sources = posix.c
libs := glib-2.0 gthread-2.0 sdl guile-2.0

include Makefile.common

$(OBJDIR)/mcmapper$(EXE): LDFLAGS += -lpng

CFLAGS += -DPLATFORM_POSIX
CFLAGS += $(shell pkg-config --cflags $(libs))
OPTCFLAGS += $(shell pkg-config --cflags $(libs))

# Apple's gcc is braindead by default.
ifeq ($(shell uname),Darwin)
        CFLAGS += -fnested-functions
endif

LDFLAGS = $(shell pkg-config --libs $(libs)) -lz -lreadline -lSDL_ttf
