static enum field_type packet_format_LOGIN[] = { FIELD_INT, FIELD_STRING, FIELD_STRING, FIELD_LONG, FIELD_BYTE };
static enum field_type packet_format_HANDSHAKE[] = { FIELD_STRING };
static enum field_type packet_format_CHAT[] = { FIELD_STRING };
static enum field_type packet_format_TIME[] = { FIELD_LONG };
static enum field_type packet_format_ENTITY_EQUIPMENT[] = { FIELD_INT, FIELD_SHORT, FIELD_SHORT, FIELD_SHORT };
static enum field_type packet_format_SPAWN_POSITION[] = { FIELD_INT, FIELD_INT, FIELD_INT };
static enum field_type packet_format_USE_ENTITY[] = { FIELD_INT, FIELD_INT, FIELD_BYTE };
static enum field_type packet_format_UPDATE_HEALTH[] = { FIELD_SHORT };
static enum field_type packet_format_PLAYER_PING[] = { FIELD_BYTE };
static enum field_type packet_format_PLAYER_MOVE[] = { FIELD_DOUBLE, FIELD_DOUBLE, FIELD_DOUBLE, FIELD_DOUBLE, FIELD_BYTE };
static enum field_type packet_format_PLAYER_ROTATE[] = { FIELD_FLOAT, FIELD_FLOAT, FIELD_BYTE };
static enum field_type packet_format_PLAYER_MOVE_ROTATE[] = { FIELD_DOUBLE, FIELD_DOUBLE, FIELD_DOUBLE, FIELD_DOUBLE, FIELD_FLOAT, FIELD_FLOAT, FIELD_BYTE };
static enum field_type packet_format_PLAYER_DIG[] = { FIELD_BYTE, FIELD_INT, FIELD_BYTE, FIELD_INT, FIELD_BYTE };
static enum field_type packet_format_PLACE[] = { FIELD_INT, FIELD_BYTE, FIELD_INT, FIELD_BYTE, FIELD_ITEM };
static enum field_type packet_format_ENTITY_HOLDING[] = { FIELD_SHORT };
static enum field_type packet_format_ENTITY_ANIMATE[] = { FIELD_INT, FIELD_BYTE };
static enum field_type packet_format_ENTITY_ACTION[] = { FIELD_INT, FIELD_BYTE };
static enum field_type packet_format_ENTITY_SPAWN_NAMED[] = { FIELD_INT, FIELD_STRING, FIELD_INT, FIELD_INT, FIELD_INT, FIELD_BYTE, FIELD_BYTE, FIELD_SHORT };
static enum field_type packet_format_ENTITY_SPAWN_PICKUP[] = { FIELD_INT, FIELD_SHORT, FIELD_BYTE, FIELD_SHORT, FIELD_INT, FIELD_INT, FIELD_INT, FIELD_BYTE, FIELD_BYTE, FIELD_BYTE };
static enum field_type packet_format_ENTITY_COLLECT[] = { FIELD_INT, FIELD_INT };
static enum field_type packet_format_ENTITY_SPAWN_OBJECT[] = { FIELD_INT, FIELD_BYTE, FIELD_INT, FIELD_INT, FIELD_INT };
static enum field_type packet_format_ENTITY_SPAWN_MOB[] = { FIELD_INT, FIELD_BYTE, FIELD_INT, FIELD_INT, FIELD_INT, FIELD_BYTE, FIELD_BYTE, FIELD_ENTITY_DATA };
static enum field_type packet_format_ENTITY_SPAWN_PAINTING[] = { FIELD_INT, FIELD_STRING, FIELD_INT, FIELD_INT, FIELD_INT, FIELD_INT };
static enum field_type packet_format_ENTITY_VELOCITY[] = { FIELD_INT, FIELD_SHORT, FIELD_SHORT, FIELD_SHORT };
static enum field_type packet_format_ENTITY_DESTROY[] = { FIELD_INT };
static enum field_type packet_format_ENTITY[] = { FIELD_INT };
static enum field_type packet_format_ENTITY_REL_MOVE[] = { FIELD_INT, FIELD_BYTE, FIELD_BYTE, FIELD_BYTE };
static enum field_type packet_format_ENTITY_LOOK[] = { FIELD_INT, FIELD_BYTE, FIELD_BYTE };
static enum field_type packet_format_ENTITY_REL_MOVE_LOOK[] = { FIELD_INT, FIELD_BYTE, FIELD_BYTE, FIELD_BYTE, FIELD_BYTE, FIELD_BYTE };
static enum field_type packet_format_ENTITY_MOVE[] = { FIELD_INT, FIELD_INT, FIELD_INT, FIELD_INT, FIELD_BYTE, FIELD_BYTE };
static enum field_type packet_format_ENTITY_DAMAGE[] = { FIELD_INT, FIELD_BYTE };
static enum field_type packet_format_ENTITY_ATTACH[] = { FIELD_INT, FIELD_INT };
static enum field_type packet_format_ENTITY_METADATA[] = { FIELD_INT, FIELD_ENTITY_DATA };
static enum field_type packet_format_PRECHUNK[] = { FIELD_INT, FIELD_INT, FIELD_BYTE };
static enum field_type packet_format_CHUNK[] = { FIELD_INT, FIELD_SHORT, FIELD_INT, FIELD_BYTE, FIELD_BYTE, FIELD_BYTE, FIELD_BYTE_ARRAY };
static enum field_type packet_format_MULTI_SET_BLOCK[] = { FIELD_INT, FIELD_INT, FIELD_BLOCK_ARRAY };
static enum field_type packet_format_SET_BLOCK[] = { FIELD_INT, FIELD_BYTE, FIELD_INT, FIELD_BYTE, FIELD_BYTE };
static enum field_type packet_format_PLAY_BLOCK[] = { FIELD_INT, FIELD_SHORT, FIELD_INT, FIELD_BYTE, FIELD_BYTE };
static enum field_type packet_format_EXPLOSION[] = { FIELD_DOUBLE, FIELD_DOUBLE, FIELD_DOUBLE, FIELD_FLOAT, FIELD_EXPLOSION_ARRAY };
static enum field_type packet_format_INVENTORY_OPEN[] = { FIELD_BYTE, FIELD_BYTE, FIELD_STRING, FIELD_BYTE };
static enum field_type packet_format_INVENTORY_CLOSE[] = { FIELD_BYTE };
static enum field_type packet_format_INVENTORY_CLICK[] = { FIELD_BYTE, FIELD_SHORT, FIELD_BYTE, FIELD_SHORT, FIELD_ITEM };
static enum field_type packet_format_INVENTORY_UPDATE[] = { FIELD_BYTE, FIELD_SHORT, FIELD_ITEM };
static enum field_type packet_format_INVENTORY_DATA[] = { FIELD_BYTE, FIELD_ITEM_ARRAY };
static enum field_type packet_format_INVENTORY_PROGRESS[] = { FIELD_BYTE, FIELD_SHORT, FIELD_SHORT };
static enum field_type packet_format_INVENTORY_ACK[] = { FIELD_BYTE, FIELD_SHORT, FIELD_BYTE };
static enum field_type packet_format_SIGN_UPDATE[] = { FIELD_INT, FIELD_SHORT, FIELD_INT, FIELD_STRING, FIELD_STRING, FIELD_STRING, FIELD_STRING };
static enum field_type packet_format_DISCONNECT[] = { FIELD_STRING };
struct packet_format_desc packet_format[] = {
  [PACKET_KEEPALIVE] = { 0, 0, 1 },
  [PACKET_LOGIN] = { 5, packet_format_LOGIN, 1 },
  [PACKET_HANDSHAKE] = { 1, packet_format_HANDSHAKE, 1 },
  [PACKET_CHAT] = { 1, packet_format_CHAT, 1 },
  [PACKET_TIME] = { 1, packet_format_TIME, 1 },
  [PACKET_ENTITY_EQUIPMENT] = { 4, packet_format_ENTITY_EQUIPMENT, 1 },
  [PACKET_SPAWN_POSITION] = { 3, packet_format_SPAWN_POSITION, 1 },
  [PACKET_USE_ENTITY] = { 3, packet_format_USE_ENTITY, 1 },
  [PACKET_UPDATE_HEALTH] = { 1, packet_format_UPDATE_HEALTH, 1 },
  [PACKET_RESPAWN] = { 0, 0, 1 },
  [PACKET_PLAYER_PING] = { 1, packet_format_PLAYER_PING, 1 },
  [PACKET_PLAYER_MOVE] = { 5, packet_format_PLAYER_MOVE, 1 },
  [PACKET_PLAYER_ROTATE] = { 3, packet_format_PLAYER_ROTATE, 1 },
  [PACKET_PLAYER_MOVE_ROTATE] = { 7, packet_format_PLAYER_MOVE_ROTATE, 1 },
  [PACKET_PLAYER_DIG] = { 5, packet_format_PLAYER_DIG, 1 },
  [PACKET_PLACE] = { 5, packet_format_PLACE, 1 },
  [PACKET_ENTITY_HOLDING] = { 1, packet_format_ENTITY_HOLDING, 1 },
  [PACKET_ENTITY_ANIMATE] = { 2, packet_format_ENTITY_ANIMATE, 1 },
  [PACKET_ENTITY_ACTION] = { 2, packet_format_ENTITY_ACTION, 1 },
  [PACKET_ENTITY_SPAWN_NAMED] = { 8, packet_format_ENTITY_SPAWN_NAMED, 1 },
  [PACKET_ENTITY_SPAWN_PICKUP] = { 10, packet_format_ENTITY_SPAWN_PICKUP, 1 },
  [PACKET_ENTITY_COLLECT] = { 2, packet_format_ENTITY_COLLECT, 1 },
  [PACKET_ENTITY_SPAWN_OBJECT] = { 5, packet_format_ENTITY_SPAWN_OBJECT, 1 },
  [PACKET_ENTITY_SPAWN_MOB] = { 8, packet_format_ENTITY_SPAWN_MOB, 1 },
  [PACKET_ENTITY_SPAWN_PAINTING] = { 6, packet_format_ENTITY_SPAWN_PAINTING, 1 },
  [PACKET_ENTITY_VELOCITY] = { 4, packet_format_ENTITY_VELOCITY, 1 },
  [PACKET_ENTITY_DESTROY] = { 1, packet_format_ENTITY_DESTROY, 1 },
  [PACKET_ENTITY] = { 1, packet_format_ENTITY, 1 },
  [PACKET_ENTITY_REL_MOVE] = { 4, packet_format_ENTITY_REL_MOVE, 1 },
  [PACKET_ENTITY_LOOK] = { 3, packet_format_ENTITY_LOOK, 1 },
  [PACKET_ENTITY_REL_MOVE_LOOK] = { 6, packet_format_ENTITY_REL_MOVE_LOOK, 1 },
  [PACKET_ENTITY_MOVE] = { 6, packet_format_ENTITY_MOVE, 1 },
  [PACKET_ENTITY_DAMAGE] = { 2, packet_format_ENTITY_DAMAGE, 1 },
  [PACKET_ENTITY_ATTACH] = { 2, packet_format_ENTITY_ATTACH, 1 },
  [PACKET_ENTITY_METADATA] = { 2, packet_format_ENTITY_METADATA, 1 },
  [PACKET_PRECHUNK] = { 3, packet_format_PRECHUNK, 1 },
  [PACKET_CHUNK] = { 7, packet_format_CHUNK, 1 },
  [PACKET_MULTI_SET_BLOCK] = { 3, packet_format_MULTI_SET_BLOCK, 1 },
  [PACKET_SET_BLOCK] = { 5, packet_format_SET_BLOCK, 1 },
  [PACKET_PLAY_BLOCK] = { 5, packet_format_PLAY_BLOCK, 1 },
  [PACKET_EXPLOSION] = { 5, packet_format_EXPLOSION, 1 },
  [PACKET_INVENTORY_OPEN] = { 4, packet_format_INVENTORY_OPEN, 1 },
  [PACKET_INVENTORY_CLOSE] = { 1, packet_format_INVENTORY_CLOSE, 1 },
  [PACKET_INVENTORY_CLICK] = { 5, packet_format_INVENTORY_CLICK, 1 },
  [PACKET_INVENTORY_UPDATE] = { 3, packet_format_INVENTORY_UPDATE, 1 },
  [PACKET_INVENTORY_DATA] = { 2, packet_format_INVENTORY_DATA, 1 },
  [PACKET_INVENTORY_PROGRESS] = { 3, packet_format_INVENTORY_PROGRESS, 1 },
  [PACKET_INVENTORY_ACK] = { 3, packet_format_INVENTORY_ACK, 1 },
  [PACKET_SIGN_UPDATE] = { 7, packet_format_SIGN_UPDATE, 1 },
  [PACKET_DISCONNECT] = { 1, packet_format_DISCONNECT, 1 },
};
